services:
  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend_container
    image: nginx:alpine
    command: nginx -g "daemon off;"
    ports:
      - "3000:80"
    expose:
      - "80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      - backend
      - db

  db:
    container_name: db_container
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
