# Generated by Django 5.2.4 on 2025-08-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="board_id",
        ),
        migrations.AddField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="todos.board",
            ),
        ),
    ]
