# Generated by Django 5.2.4 on 2025-08-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_remove_task_board_id_task_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="todos.board",
            ),
        ),
    ]
